### ISSUE TITLE
Error in running Material ui webpack example

### ISSUE THREAD

**Issue by mhtaheri** [callemall/material-ui-webpack-example#8]
I'm trying to run material ui webpack example but after npm start i have get below error:

![image](https://cloud.githubusercontent.com/assets/22958743/23601005/8af1694e-025e-11e7-84a5-e8bfba08493b.png)

Node -v:
v7.4.0

How can fix it?

**Comment by oliviertassinari** [comment]
That looks like an issue with Babel, weird. Let us know if you figure out what's wrong.

**Comment by geeeeeeeeek** [comment]
@oliviertassinari Same issue here.

**Comment by oliviertassinari** [comment]
@geeeeeeeeek Do you have a `.babelrc` file higher in the folder tree? That could mess things around.

**Comment by geeeeeeeeek** [comment]
@oliviertassinari Nope. I don't think so. The folder is clean.

**Comment by geeeeeeeeek** [comment]
![image](https://cloud.githubusercontent.com/assets/7262715/26251304/680af344-3cdf-11e7-8697-e2ff5993b2b4.png)

@oliviertassinari Root cause found. Please update your package versions as above. Refer to [a similar issue](https://github.com/prescottprue/generator-react-firebase/issues/27) for more specific explanations.

**Comment by oliviertassinari** [comment]
@geeeeeeeeek Thanks for sharing the solution!
